# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
platform :ios, '13.0'

target '01_RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 01_RxSwift
    # ++
    pod 'RxSwift', '6.6.0'
    pod 'RxCocoa', '6.6.0'

end
