# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ReactivePrograming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactivePrograming
    pod 'RxSwift', '6.7.1'
    pod 'RxCocoa', '6.7.1'

end
