# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MVVM&CodeUI&CollectionView' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# Pods for MVVM&CodeUI&CollectionView
pod 'Kingfisher', '~> 7.0'
pod 'SnapKit'
pod 'RxSwift', '6.6.0'
pod 'RxCocoa', '6.6.0'
pod 'RxAlamofire'

end
